[platformio]
default_envs = m5stickc_plus_smoke

[env:m5stickc_plus_smoke]
platform = espressif32
board = m5stick-c
framework = arduino
upload_port = COM3
monitor_port = COM3
monitor_speed = 115200
upload_speed = 1500000
build_flags =
  -DCORE_DEBUG_LEVEL=0
